### ISSUE TITLE
本のモデルクラスを作成する

### ISSUE THREAD

**Issue by hiratatsu04** [hiratatsu04/booknote#5]
# 振る舞い（操作）

- 各種属性を登録・更新する
- 購入日・読書開始日・終了日のコンボボックスの値をdate型に変換する

# 属性

- タイトル
- 著者名
- イメージ画像
- ジャンル
- 評価値
- 購入日
- 読書開始日
- 読書終了日
- 感想

**Comment by kiyoshin** [comment]
DB設計を行ってからがいいと思いますが、各属性の型も考えてみてください。

**Comment by hiratatsu04** [comment]
# 振る舞い（操作）

- 各種属性を登録・更新する
- 購入日・読書開始日・終了日のコンボボックスの値をdate型に変換する

# 属性

- タイトル
- 著者名
- イメージ画像
- ジャンル
- 評価値
- 購入日
- 読書開始日
- 読書終了日
- 感想

**Comment by hiratatsu04** [comment]
DBのテーブル定義を検討いたしました。

# 振る舞い（操作）

- 各種属性をDBへ登録する
- DBの各種属性を更新する

# 属性＋テーブル定義

物理名 | 論理名 | データ型 | 非null | Primary Key | 自動増加 | UNIQUE | デフォルト値 | 外部キー
-- | -- | -- | -- | -- | -- | -- | -- | --
id | id | INTEGER | ✓ | ✓ | ✓ | (✓) | (自動増加) | －
title | 書籍タイトル | TEXT | ✓ | － | － | － | － | －
author | 書籍著者 | TEXT | ✓ | － | － | － | － | －
book_image | 書籍の表紙画像 | BLOB | － | － | － | － | － | －
genre | 書籍のジャンル | TEXT | － | － | － | － | － | －
review_value | 読書後評価 | REAL | － | － | － | － | － | －
memo | 読書後の感想 | TEXT | － | － | － | － | － | －
buy_date | 購入日 | TEXT | ✓ | － | － | － | － | －
start_date | 読書開始の年月日 | TEXT | － | － | － | － | － | －
end_date | 読書終了の年月日 | TEXT | － | － | － | － | － | －
recode_date | アプリへの登録年月日 | TEXT | ✓ | － | － | － | レコード登録日 | －
update_date | 登録情報の更新年月日 | TEXT | ✓ | － | － | － | － | －

**Comment by hiratatsu04** [comment]
データベースとのやり取りは専用のクラスを用意する。

# 振る舞い（操作）

なし

# 属性＋テーブル定義

物理名 | 論理名 | データ型 | 非null | Primary Key | 自動増加 | UNIQUE | デフォルト値 | 外部キー
-- | -- | -- | -- | -- | -- | -- | -- | --
id | id | INTEGER | ✓ | ✓ | ✓ | (✓) | (自動増加) | －
title | 書籍タイトル | TEXT | ✓ | － | － | － | － | －
author | 書籍著者 | TEXT | ✓ | － | － | － | － | －
book_image | 書籍の表紙画像 | BLOB | － | － | － | － | － | －
genre | 書籍のジャンル | TEXT | － | － | － | － | － | －
review_value | 読書後評価 | REAL | － | － | － | － | － | －
memo | 読書後の感想 | TEXT | － | － | － | － | － | －
buy_date | 購入日 | TEXT | ✓ | － | － | － | － | －
start_date | 読書開始の年月日 | TEXT | － | － | － | － | － | －
end_date | 読書終了の年月日 | TEXT | － | － | － | － | － | －
recode_date | アプリへの登録年月日 | TEXT | ✓ | － | － | － | レコード登録日 | －
update_date | 登録情報の更新年月日 | TEXT | － | － | － | － | － | －
